# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171019_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lab',
            field=models.CharField(blank=True, choices=[('St-Johns', 'St-Johns'), ('Dartmouth', 'Dartmouth'), ('Charlottetown', 'Charlottetown'), ('St-Hyacinthe', 'St-Hyacinthe'), ('Longeuil', 'Longeuil'), ('Fallowfield', 'Fallowfield'), ('Carling', 'Carling'), ('Greater Toronto Area', 'Greater Toronto Area'), ('Winnipeg', 'Winnipeg'), ('Saskatoon', 'Saskatoon'), ('Calgary', 'Calgary'), ('Lethbridge', 'Lethbridge'), ('Burnaby', 'Burnaby'), ('Sidney', 'Sidney'), ('N/A', 'N/A')], default=15, max_length=100),
        ),
    ]
