# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-20 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import olc_webportalv2.cowbat.models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=olc_webportalv2.cowbat.models.get_run_name)),
            ],
        ),
        migrations.RemoveField(
            model_name='sequencingrun',
            name='samplesheet',
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='run_name',
            field=models.CharField(default='asdf', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='sequencing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafile', to='cowbat.SequencingRun'),
        ),
    ]
