# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0002_auto_20180620_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='status',
            field=models.CharField(default='Unprocessed', max_length=64),
        ),
    ]
