# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-04 20:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0003_remove_sequencingrun_seqids'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='seqids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=[], size=None),
        ),
    ]
