# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import olc_webportalv2.cowbat.models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0004_sequencingrun_seqids'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterOpFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interop_file', models.FileField(upload_to=olc_webportalv2.cowbat.models.get_interop_name)),
                ('sequencing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interop', to='cowbat.SequencingRun')),
            ],
        ),
    ]
