# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import olc_webportalv2.projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_R1', models.FileField(blank=True, upload_to=olc_webportalv2.projects.models.generate_path)),
                ('file_R2', models.FileField(blank=True, upload_to=olc_webportalv2.projects.models.generate_path)),
                ('organism', models.CharField(blank=True, max_length=256)),
                ('reference', models.CharField(blank=True, max_length=256)),
                ('type', models.CharField(blank=True, max_length=128)),
                ('genesippr_results', models.CharField(blank=True, max_length=128)),
                ('requested_jobs', multiselectfield.db.fields.MultiSelectField(choices=[('genesipprv2', 'GENESIPPRV2'), ('fastqc', 'FASTQC')], max_length=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
