# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171003_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_R1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='file_R2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
