# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_genesipprresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesipprresults',
            name='genus',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='strain',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
