# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20171005_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genesipprresults',
            old_name='project_id',
            new_name='project',
        ),
    ]
