# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20171006_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesipprresults',
            name='eae',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='gdcs',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='gdcs_coverage',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='hyla',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='igs',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='inij',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='inva',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='pass_fail',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='serotype',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='stn',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='stx1',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='stx2',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='stx2f',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='uida',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
