# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20171006_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genesipprresults',
            name='eae',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='hyla',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='igs',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='inij',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='inva',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='serotype',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='stn',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='stx1',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='stx2',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='stx2f',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='uida',
        ),
    ]
