# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-19 18:56
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20171018_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requested_jobs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('genesipprv2', 'GenesipprV2'), ('schnoodleshnorp', 'SchnoodleShnorprr'), ('gloobleshteen', 'Gloobleshteen')], max_length=41),
        ),
    ]
