# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import olc_webportalv2.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20171019_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_R1',
            field=models.FileField(blank=True, upload_to='', validators=[olc_webportalv2.projects.models.validate_fastq]),
        ),
        migrations.AlterField(
            model_name='project',
            name='file_R2',
            field=models.FileField(blank=True, upload_to='', validators=[olc_webportalv2.projects.models.validate_fastq]),
        ),
    ]
