# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 18:27
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20171020_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requested_jobs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('genesipprv2', 'GenesipprV2'), ('sendsketch', 'sendsketch'), ('gloobleshteen', 'Gloobleshteen')], max_length=36),
        ),
    ]
