# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20171020_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendsketchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sendsketch_status',
            field=models.CharField(default='Unprocessed', max_length=128),
        ),
        migrations.AddField(
            model_name='sendsketchresults',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
