# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20171023_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genesipprresults',
            old_name='gdcs',
            new_name='eae',
        ),
        migrations.RenameField(
            model_name='genesipprresults',
            old_name='gdcs_coverage',
            new_name='eae_1',
        ),
        migrations.RenameField(
            model_name='genesipprresults',
            old_name='pass_fail',
            new_name='gdcs_genus',
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='gdcs_matches',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='hyla',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='igs',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='inlj',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='inva',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o103',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o111',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o121',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o145',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o157',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o26',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o45',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='sixteens_foldcoverage',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='sixteens_gene',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='sixteens_genus',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='sixteens_percentidentity',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='stn',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='uida',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='vt1',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='vt2',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='vt2f',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
