# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20171024_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenesipprResultsGDCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(default='N/A', max_length=256)),
                ('genus', models.CharField(default='N/A', max_length=256)),
                ('matches', models.CharField(default='N/A', max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='GenesipprResultsSerosippr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='GenesipprResultsSixteens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(default='N/A', max_length=256)),
                ('gene', models.CharField(default='N/A', max_length=256)),
                ('percentidentity', models.CharField(default='N/A', max_length=256)),
                ('genus', models.CharField(default='N/A', max_length=256)),
                ('foldcoverage', models.CharField(default='N/A', max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='gdcs_genus',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='gdcs_matches',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='sixteens_foldcoverage',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='sixteens_gene',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='sixteens_genus',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='sixteens_percentidentity',
        ),
    ]
