# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20171024_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genesipprresultsgdcs',
            options={'verbose_name_plural': 'GDCS Results'},
        ),
        migrations.AlterModelOptions(
            name='genesipprresultsserosippr',
            options={'verbose_name_plural': 'Serosippr Results'},
        ),
        migrations.AlterModelOptions(
            name='genesipprresultssixteens',
            options={'verbose_name_plural': 'SixteenS Results'},
        ),
    ]
