# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20171024_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genesipprresults',
            old_name='o103',
            new_name='serotype',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='o111',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='o121',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='o145',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='o157',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='o26',
        ),
        migrations.RemoveField(
            model_name='genesipprresults',
            name='o45',
        ),
    ]
