# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20171025_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesipprresults',
            name='o103',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o111',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o121',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o145',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o157',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o26',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='o45',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
