# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import olc_webportalv2.projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0021_auto_20171025_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_R1', models.FileField(blank=True, upload_to='', validators=[olc_webportalv2.projects.models.validate_fastq])),
                ('file_R2', models.FileField(blank=True, upload_to='', validators=[olc_webportalv2.projects.models.validate_fastq])),
                ('organism', models.CharField(blank=True, max_length=256)),
                ('reference', models.CharField(blank=True, max_length=256)),
                ('type', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='file_R1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='file_R2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='project',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_project', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
