# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import olc_webportalv2.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20171025_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='file_R1',
            field=models.FileField(blank=True, upload_to='', validators=[olc_webportalv2.projects.models.validate_fastq]),
        ),
        migrations.AddField(
            model_name='project',
            name='file_R2',
            field=models.FileField(blank=True, upload_to='', validators=[olc_webportalv2.projects.models.validate_fastq]),
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
