# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import olc_webportalv2.new_multisample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMulti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_R1', models.FileField(blank=True, upload_to='', validators=[olc_webportalv2.new_multisample.models.validate_fastq])),
                ('file_R2', models.FileField(blank=True, upload_to='', validators=[olc_webportalv2.new_multisample.models.validate_fastq])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_multisample.ProjectMulti')),
            ],
        ),
    ]
