# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_multisample', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(default='file.txt', max_length=200),
        ),
    ]
