# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_multisample', '0002_amrresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='amr_status',
            field=models.CharField(default='Unprocessed', max_length=128),
        ),
    ]
