# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_multisample', '0003_attachment_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='project',
        ),
    ]
