# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 18:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_multisample', '0003_sample_amr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amrresult',
            name='results_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
