# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 18:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_multisample', '0004_auto_20180322_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genesipprresultsgdcs',
            name='allele_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
