# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_multisample', '0005_auto_20180322_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='amrresult',
            name='species',
            field=models.CharField(default='N/A', max_length=88),
        ),
    ]
