# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-05 15:21
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('new_multisample', '0006_auto_20180305_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmulti',
            name='requested_jobs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('genesipprv2', 'GenesipprV2'), ('sendsketch', 'sendsketch')], default='asdf', max_length=22),
            preserve_default=False,
        ),
    ]
